### ISSUE TITLE
next time, check your messages

### ISSUE THREAD

**Issue by stylemessiah** [canyie/Riru-IsolatedMagiskHider#16]
instead of waiting 2 months and trolling me on telegram like a petualant child

ive removed my mod from XDA, where i openly credited you for your original module and noted distinctly my additions to your script on that page, so that others could add it if they wanted, while i also attached a working module.

that thread is one of the most active on XDA, and watched like a hawk for any post which dont make the grade or correctly credit people, and in 2 months no one saw an issue with my post. 

You decided to act like a child tonight on Telegram, so my post reflects that

Enjoy whats now there explaining your poor behaviour:

https://forum.xda-developers.com/t/magisk-general-support-discussion.3432382/post-85187739

Also as a reference see here in my own modules how i credit people, i did no different on that post AND i notified you, not my fault if you ignored it...

https://github.com/stylemessiah/GPay-SQLite-Fix/blob/master/common/install.sh

**Comment by canyie** [comment]
1. Where is the message you sent? I have checked my e-mail, telegram, github issues and QQ group, can't find anything.
2. This project is under GPL V3, so of course, you can modify it and release a mod build, that's your freedom -- but you have to comply with the GPL V3 license. This license  requires you to attach the complete source code instead of a patch. Ask the Free Software Foundation for why, instead of accusing me of breaking your good mod. https://www.gnu.org/licenses/gpl-faq.en.html#DistributingSourceIsInconvenient
3. Instead of answering the question positively, you repeatedly stressed that you are 50 years old and accused us of "being a petualant child" -- Yes I am a child, I'm not even an adult, but you are more childish than me.

**Comment by canyie** [comment]
Just pinned this issue, now enjoy whats now there explaining your poor behaviour
